<a href="https://colab.research.google.com/github/Minkeez/Pytorch-Tutorial/blob/main/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# LISTs

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy Arrays

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.99562375, 0.21270774, 0.48392496, 0.9339603 ],
       [0.51227841, 0.73887534, 0.71274515, 0.95146939],
       [0.69335175, 0.17402322, 0.78124603, 0.12846471]])

In [5]:
np1.dtype

dtype('float64')

# Tensors

In [10]:
tensor_2d = torch.randn(3, 4)
tensor_2d
# tensor_2d.dtype

tensor([[-0.0283,  0.9732,  1.3487,  1.1873],
        [ 1.2141,  0.0053,  0.2633, -2.2273],
        [ 1.4227, -0.2434,  0.1146, -0.9128]])

In [7]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Creatw tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9956, 0.2127, 0.4839, 0.9340],
        [0.5123, 0.7389, 0.7127, 0.9515],
        [0.6934, 0.1740, 0.7812, 0.1285]], dtype=torch.float64)

In [ ]:
edit