<a href="https://colab.research.google.com/github/Minkeez/Pytorch-Tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### TENSOR MATH OPERATIONS
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and uh, Longhand
- Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

# Addition

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

# Addition Longhand

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

# Subtraction

In [5]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

# Sub Function

In [6]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

# Multiplication

In [7]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

# Mul Longhand

In [9]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

# Division

In [10]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

# Division Longhand

In [11]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

# Remainder Modulus

In [12]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

# Remainder Longhand

In [14]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

# Exponents / power

In [15]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

# Another way to write longhand

In [16]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

# Reassignment

In [17]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([1, 2, 3, 4])

In [20]:
tensor_a.add_(tensor_b) # reassign back to variable

tensor([ 6,  8, 10, 12])

In [21]:
tensor_a

tensor([ 6,  8, 10, 12])